/**
 * USER
 */
export const START_FETCHING_USER = 'START_FETCHING_USER';
export const RECEIVED_USER = 'RECEIVED_USER';
export const ERROR_FETCHING_USER = 'ERROR_FETCHING_USER';

/**
 * EDITOR
 */
export const START_FETCHING_UNASSIGNED_SUBMISSIONS =
  'START_FETCHING_UNASSIGNED_SUBMISSIONS';

export const RECEIVED_UNASSIGNED_SUBMISSIONS =
  'RECEIVED_UNASSIGNED_SUBMISSIONS';

export const ERROR_FETCHING_UNASSIGNED_SUBMISSIONS =
  'ERROR_FETCHING_UNASSIGNED_SUBMISSIONS';

export const START_FETCHING_ARTICLES_TO_SIGNOFF =
  'START_FETCHING_ARTICLES_TO_SIGNOFF';

export const RECEIVED_ARTICLES_TO_SIGNOFF = 'RECEIVED_ARTICLES_TO_SIGNOFF';

export const ERROR_FETCHING_ARTICLES_TO_SIGNOFF =
  'ERROR_FETCHING_ARTICLES_TO_SIGNOFF';

/**
 * Transactions
 */
export const START_FETCHING_TXS = 'START_FETCHING_TXS';
export const RECEIVED_TXS = 'RECEIVED_TXS';
export const ERROR_FETCHING_TXS = 'ERROR_FETCHING_TXS';
export const ADDING_TX = 'ADDING_TX';
export const ADDED_TX = 'ADDED_TX';
export const ERROR_ADDING_TX = 'ERROR_ADDING_TX';

/**
 * OTHERS
 */
export const SET_NETWORK = 'SET_NETWORK';
export const SET_METAMASK = 'SET_METAMASK';
export const SETTING_ACCOUNTS = 'SETTING_ACCOUNTS';
export const ACCOUNTS_SET = 'ACCOUNTS_SET';
export const ACCOUNTS_ERROR = 'ACCOUNTS_ERROR';

/**
 * Articles
 */
export const START_FETCHING_ONLINE_DRAFTS = 'START_FETCHING_ONLINE_DRAFTS';
export const RECEIVED_ONLINE_DRAFTS = 'RECEIVED_ONLINE_DRAFTS';
export const ERROR_FETCHING_ONLINE_DRAFTS = 'ERROR_FETCHING_ONLINE_DRAFTS';

/**
 * Article
 */
export const START_FETCHING_ARTICLE_DATA = 'START_FETCHING_ARTICLE_DATA';
export const RECEIVED_ARTICLE_DATA = 'RECEIVED_ARTICLE_DATA';
export const ERROR_FETCHING_ARTCLE_DATA = 'ERROR_FETCHING_ARTCLE_DATA';

/**
 * Reviews
 */
export const START_FETCH_ARTICLES_OPEN_TO_REVIEW =
  'FETCH_ARTICLES_OPEN_TO_REVIEW';
export const RECEIVED_ARTICLES_OPEN_TO_REVIEW =
  'RECEIVED_ARTICLES_OPEN_TO_REVIEW';
export const ERROR_ARTICLES_OPEN_TO_REVIEW = 'ERROR_ARTICLES_OPEN_TO_REVIEW';

/**
 * Reviewer
 */
export const BECOMING_A_REVIEWER = 'BECOMING_A_REVIEWER';
export const BECAME_A_REVIEWER = 'BECAME_A_REVIEWER';
export const ERROR_BECOMING_A_REVIEWER = 'ERROR_BECOMING_A_REVIEWER';

/**
 * Modal
 */

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
